### ISSUE TITLE
Editor button icons prevent button tooltips and hover color tint [bug]

### ISSUE THREAD

**Issue by Dragoneles** [douglasZwick/blb#19]
**Describe the bug**
Tooltips don't display when the cursor is over the icon of a button- only when the cursor is on the edges of the button.

**Tell us how to reproduce it**
Please provide a list of steps to reproduce the behavior:
1) Place mouse cursor over center of editor button (no tooltip)
2) Move cursor to edges of editor button (tooltip appears)

**Tell us the expected behavior**
Please provide a clear and concise description of what you expected to happen.
Tooltips should also be displayed when placing the mouse cursor at the center of any editor button.

**Tell us about the version you're using**
Please provide the following version information:
 - Platform: in Unity editor (v2021.3.1f1)
 - Version 0.9.4

**Do you have any additional insight?**
Add any other context about the problem here, or feel free to speculate about the cause of the bug.
Disabling the [Raycast Target] flag on the button icons should resolve the issue.

**Comment by douglasZwick** [comment]
Fixed in v0.9.50.
