### ISSUE TITLE
Section Death Counter [fr]

### ISSUE THREAD

**Issue by MacMan23** [douglasZwick/blb#29]
**Tell us the feature you'd like**
When a level is played and finished, player deaths for each section are totaled.
A section is classified as a region between checkpoints, the start, or the goal.
The death total is displayed in the editor above the checkpoint/goal the marks the end of a section.
If a level is played again the sections death is added the to running total.
The sections deaths will be saved into the level file.
If a change is made to the level, the death counters are reset.

**Tell us about the alternatives you've considered**
For each playtest, the data could instead be exported to a playtest file that lists the level name/version and the deaths of each section. Multiple playtests on the same level version will add to the files death count.

**Comment by douglasZwick** [comment]
This is similar enough to #39, which is even more useful, so we won't do it.
