### ISSUE TITLE
No player warning [fr]

### ISSUE THREAD

**Issue by MacMan23** [douglasZwick/blb#36]
**Is this feature request related to an existing problem? Tell us about it if so**
When entering play mode with no player it will still enter play mode but with no ability to move a player.

**Tell us the feature you'd like**
Add a warning if there is no player in scene when entering play mode, and don't enter play mode.

**Comment by douglasZwick** [comment]
Rather than preventing starting altogether, I would prefer to just fix the camera behavior. However, I do like the idea of having a warning.
