### ISSUE TITLE
Copy/Paste key combo should use CTRL [fr]

### ISSUE THREAD

**Issue by MacMan23** [douglasZwick/blb#47]
**Is this feature request related to an existing problem? Tell us about it if so**
When I go to copy and paste, my goto key combo is CTRL+C/V, yet in the editor it is SHIFT_C/V

**Tell us the feature you'd like**
Either change the key combo to use CTRL, or make that an alternative key combo.

**Comment by douglasZwick** [comment]
Well, it does. This is more of an issue of communicating the actual functionality, and that's already been commented on in #56. Closing, and we can new issues or tasks based on the comment in that issue.
